name: Nix

on:
  push

jobs:
  tets:
    runs-on: ubuntu-20.04
    container: nixpkgs/nix
    steps:
      - uses: actions/checkout@v2
      - run: echo "Test"      
      # - run: |
      #     nix-shell --run "uname -a"
